trigger:
  branches:
   include:
    - main
pool:
  name: Azure Pipelines

stages:
  - stage: Build
    displayName: 'Build Stage'

jobs: Copy Artifact

    job: copy artifact
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: utils
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: utils
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

steps:
- task: AzureFileCopy@3
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/_databricksproject-CI/drop'
    azureSubscription: databricksproject
    Destination: AzureBlob
    storage: adestorage99
    ContainerName: copysample
    sasTokenTimeOutInMinutes: 240