trigger:
- none

pool:
  vmImage: 'windows-latest'

  variables:
    - group: databricks-var-kv
  
stages:
- stage: Upload_Blob_to_Storage_Account
  displayName: 'Upload Blob to Storage Account'
  jobs:
  - job:
    displayName: Copy from Source to Destination
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: utils
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
     
    - task: AzureFileCopy@3
      displayName: 'AzureBlob File Copy'
      inputs:
        SourcePath: '$(Build.ArtifactStagingDirectory)/sample.json'
        azureSubscription: $'(azureSubscription)'
        Destination: 'AzureBlob'
        storage: $(storage)
        ContainerName: $(ContainerName)
        outputStorageUri: $(outputStorageUri)
        outputStorageContainerSasToken: $(outputStorageContainerSasToken)
        sasTokenTimeOutInMinutes: $(sasTokenTimeOutInMinutes)


- stage: Upload_to_Notebooks
  displayName: Upload to Notebooks
  dependsOn: Upload_Blob_to_Storage_Account
  condition: succeeded('Upload_Blob_to_Storage_Account')
  jobs:
  - job:
    displayName: Copy from Source Databrick
    steps:
    - task: CopyFiles@2
      inputs:
       SourceFolder: 'databricks'
       Contents: '**/*.py'
       TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - script: dir $(Build.ArtifactStagingDirectory)

    - task: configuredatabricks@0
      inputs:
       url: $(url)
       token: $(token)

    - task: deploynotebooks@0
      inputs:
        notebooksFolderPath: '$(Build.ArtifactStagingDirectory)'
        workspaceFolder: '/Shared'
