trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadSecureFile@1
  name: 'GetFile'
  displayName: 'Download file from secure location'
  inputs:
    secureFile: 'storage.json'

- script: |
    az storage blob upload-batch --destination databricksproject --destination-path databricksproject --source C:\Users\scopn\OneDrive\Desktop --pattern sample.json
  displayName: 'Upload file to storage'
  env:
    AZURE_STORAGE_CONNECTION_STRING: $(storageConnectionString)
