trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage:
  jobs:
  - job:
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: utils
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: utils
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      
    - task: AzureFileCopy@3
      displayName: 'AzureBlob File Copy'
      inputs:
        SourcePath: '$(System.DefaultWorkingDirectory)/_databricksproject-CI/drop'
        azureSubscription: databricksproject
        Destination: AzureBlob
        storage: adestorage99
        ContainerName: copysample
        sasTokenTimeOutInMinutes: 240